### ISSUE TITLE
Does not work on IE11

### ISSUE THREAD

**Issue by tsuyoshiwada** [komachi/postcss-dialog-polyfill#1]
Hi @komachi, Thank you for useful library :+1:

In IE 11, unless the selector is completely separated, the expected operation is not performed.

## Actual behavior

```css
#dialog::backdrop, #dialog + .backdrop {
  background: rgba(0, 0, 0, 0.85);
}
```

## Expected behavior

```css
#dialog::backdrop {
  background: rgba(0, 0, 0, 0.85);
}

#dialog + .backdrop {
  background: rgba(0, 0, 0, 0.85);
}
```

You can check the actual behavior with the following repository.
https://github.com/tsuyoshiwada/dialog-polyfill-on-ie11
